nxp-imx8: Add imx-vpu-hantro-vc configuration and KERNEL_DEVICETREE_BASENAME
Issue: LIN1023-3220

Add these two missing configurations, otherwise this will
cause errors when compiling imx-boot and GPU packages.

ERROR: Nothing PROVIDES 'imx-vpu-hantro-vc'
arch/arm/dts/.dtb': No such file or directory

Signed-off-by: Xiaolei Wang <xiaolei.wang@windriver.com>