nxp-imx8: README.proprietary: add recipes fftw & imagemagick
Issue: LIN1024-2581

To fix below building issue:
ERROR: Nothing PROVIDES 'imagemagick-native' (but layers/meta-openembedded/meta-oe/recipes-devtools/giflib/giflib_5.2.2.bb,
virtual:multilib:lib32:layers/meta-openembedded/meta-oe/recipes-devtools/giflib/giflib_5.2.2.bb DEPENDS on or otherwise requires it)
imagemagick-native was skipped: Not supported in this configuration by Wind River. To override, add to your local.conf:
CUSTOMER_RECIPES:openembedded-layer += 'fftw'
CUSTOMER_RECIPES:openembedded-layer += 'imagemagick'

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>